name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.ndsn.cn", custom_domain = true },
  { pattern = "quay.ndsn.cn", custom_domain = true },
  { pattern = "gcr.ndsn.cn", custom_domain = true },
  { pattern = "k8s-gcr.ndsn.cn", custom_domain = true },
  { pattern = "k8s.ndsn.cn", custom_domain = true },
  { pattern = "ghcr.ndsn.cn", custom_domain = true },
  { pattern = "cloudsmith.ndsn.cn", custom_domain = true },
]

MODE = "production"
TARGET_UPSTREAM = ""
